query CartInput {
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          product {
            volumeTiers: metafield(namespace: "custom", key: "volume_tiers") {
              jsonValue
            }
          }
        }
      }
    }
  }
  shop {
    volumeTierBands: metafield(namespace: "custom", key: "volume_tier_bands") {
      jsonValue
    }
  }
  discount {
    discountClasses
  }
}
